name: dropdown_pro_example
description: An example app for the dropdown_pro package

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dropdown_pro:
    path: ../ # Path to the main `dropdown_pro` package

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
